<script>
    import { createEventDispatcher } from "svelte";
    import { fade } from "svelte/transition";
    import { bookmarksStore, removeBookmark, saveBookmarks } from "./bookmarks";
    import { buildAttackLayer } from "./attack";
    import BackButton from "./BackButton.svelte";

    const dispatch = createEventDispatcher();

    let exportDomain = "enterprise-attack";
    let defaultExportTitle = "Generated by ATT&CK Powered Suit";
    let colorBy = "Score";
    

    function exportAttackLayer() {
        // Set up the data to export.
        let exportTitle = document.getElementById('layerTitle').value || defaultExportTitle;
        let colorFlag = (colorBy == "Color")
        const data = buildAttackLayer(
            exportDomain,
            exportTitle,
            $bookmarksStore,
            colorFlag
        );

        // Do the export.
        const blob = new Blob([JSON.stringify(data)], {
            type: "application/json",
        });
        const url = URL.createObjectURL(blob);
        const anchor = document.createElement("a");
        anchor.style.display = "none";
        anchor.download = "attack_navigator_layer.json";
        anchor.href = url;
        anchor.click();
        URL.revokeObjectURL(url);
    }
</script>

<BackButton on:back={() => dispatch("showSearch")} />
<h2>ATT&CK Powered Suit</h2>
<h3><i class="bi bi-bookmark-fill" /> Bookmarks</h3>

<table class="table">
    <thead>
        <tr>
            <th><!--Bookmark icon column--></th>
            <th>Object ID</th>
            <th>Name</th>
            {#if colorBy == "Color"}
                <th>Color</th>
            {/if}
            {#if colorBy == "Score"}
                <th>Score</th>
            {/if}
            <th>Notes</th>
        </tr>
    </thead>
    <tbody>
        {#if $bookmarksStore.length == 0}
            <tr>
                <td class="nothing-found" colspan="999"
                    >Create a bookmark by clicking the <i
                        class="bi bi-bookmark-plus-fill"
                    /> next to any search result.</td
                >
            </tr>
        {/if}
        {#each $bookmarksStore as bookmark, bookmarkIdx (bookmark.id)}
            <tr out:fade>
                <td
                    ><i
                        on:click={() => removeBookmark(bookmark.id)}
                        title="Remove this bookmark"
                        class="bookmark-icon bi bi-bookmark-check-fill"
                    /></td
                >
                <td>{bookmark.id}</td>
                <td>{bookmark.name}</td>
                {#if colorBy == "Color"}
                    <td
                        ><input
                            type="color"
                            class="form-control color-picker"
                            bind:value={bookmark.color}
                            on:input={saveBookmarks}
                        /></td
                    >
                {/if}
                {#if colorBy == "Score"}
                    <td>
                        <input
                            type="number"
                            class="form-control score-input"
                            bind:value={bookmark.score}
                            on:input={saveBookmarks}
                        />
                    </td>
                {/if}
                <td
                    ><input
                        type="text"
                        class="form-control"
                        bind:value={bookmark.notes}
                        on:input={saveBookmarks}
                    /></td
                >
            </tr>
        {/each}
    </tbody>
</table>

<div class="gray-box">
    <p class="text-muted small">
        Export bookmarks for use in <a
            href="https://mitre-attack.github.io/attack-navigator/"
            target="_blank"
            >ATT&amp;CK Navigator <i class="bi bi-box-arrow-up-right" /></a
        >
    </p>
    <form on:submit={(e) => e.preventDefault()}>
        <div class="row">
            <div class="col">
                <label for="color_by">Color techniques by: </label>
                <select name="color_by" bind:value={colorBy}>
                    <option
                        value="Score"
                    >Score</option>
                    <option
                        value="Color"
                    >Color</option>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-floating">
                    <input
                        id="attackDomain"
                        type="text"
                        class="form-control"
                        placeholder="ATT&amp;CK Domain"
                        value="enterprise-attack"
                        required
                    />
                    <label for="attackDomain">ATT&amp;CK Domain</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating">
                    <input
                        id="layerTitle"
                        type="text"
                        class="form-control"
                        placeholder="Layer Title"
                        value="Generated by ATT&CK Powered Suit"
                        required
                    />
                    <label for="layerTitle">Layer Title</label>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <button
                    class="btn btn-primary"
                    on:click={() => exportAttackLayer()}
                >
                    <i class="bi bi-download" /> Export
                </button>
            </div>
        </div>
    </form>
</div>

<style>
    form .row {
        margin-bottom: 0.5rem;
    }

    .bookmark-icon {
        cursor: pointer;
        color: var(--me-ext-green-dark);
        font-size: 1.4em;
    }

    .bookmark-icon:hover {
        color: var(--me-ext-green-highlighter);
    }

    .color-picker {
        display: inline-block;
        height: 2em;
        width: 2em;
        padding: 3px;
        margin: 0;
    }

    .color-picker:disabled {
        opacity: .25;
    }

    .score-input {
        width: 3.5em;
    }

    .default-color-group label {
        position: relative;
        top: -0.3em;
    }
</style>
