<script>
    import { createEventDispatcher } from "svelte";
    import { fade } from "svelte/transition";
    import { bookmarksStore, removeBookmark, saveBookmarks } from "./bookmarks";
    import { buildAttackLayer } from "./attack";
    import BackButton from "./BackButton.svelte";
    import { lookupAttack } from "./search";

    const dispatch = createEventDispatcher();

    let exportDomain = "enterprise-attack";
    let defaultExportTitle = "Generated by ATT&CK Powered Suit";
    let colorBy = "Color";
    let accordionSelected = null;

    function exportCsv() {
        // Set up the data to export.
        const colorCol = colorBy === "Color" ? "color" : "score";
        const data = [
            `object_id,type,name,description,url,${colorCol},notes\r\n`,
        ];
        for (const bookmark of $bookmarksStore) {
            const obj = lookupAttack(bookmark.id);
            const row = [
                bookmark.id,
                obj.type,
                bookmark.name,
                obj.description,
                obj.url,
                colorBy === "Color"
                    ? bookmark.color
                    : bookmark.score.toString(),
                bookmark.notes,
            ];
            data.push(
                row
                    .map((s) => s.replaceAll('"', '""'))
                    .map((s) => `"${s}"`)
                    .join() + "\r\n"
            );
        }

        // Do the export.
        const blob = new Blob(data, {
            type: "text/csv",
        });
        const url = URL.createObjectURL(blob);
        const anchor = document.createElement("a");
        anchor.style.display = "none";
        anchor.download = "powered_suit_boomarks.csv";
        anchor.href = url;
        anchor.click();
        URL.revokeObjectURL(url);
    }

    function exportAttackLayer() {
        // Set up the data to export.
        let exportDomain = document.getElementById("attackDomain").value;
        let exportTitle =
            document.getElementById("layerTitle").value || defaultExportTitle;
        let colorFlag = colorBy == "Color";
        let techniques = [];
        for (const bookmark of $bookmarksStore) {
            const obj = lookupAttack(bookmark.id);
            if (
                bookmark.type == "technique" ||
                bookmark.type == "subtechnique"
            ) {
                techniques.push(bookmark.id);
            } else if (typeof obj.relatedTechniques !== "undefined") {
                for (const rt of obj.relatedTechniques) {
                    console.log("rt", rt);
                    techniques.push({
                        id: rt,
                        color: bookmark.color,
                        score: bookmark.score,
                        notes:
                            bookmark.notes +
                            ` (Related to bookmark: ${bookmark.id})`,
                    });
                }
            }
            console.log(techniques);
        }
        const data = buildAttackLayer(
            exportDomain,
            exportTitle,
            techniques,
            colorFlag
        );

        // Do the export.
        const blob = new Blob([JSON.stringify(data)], {
            type: "application/json",
        });
        const url = URL.createObjectURL(blob);
        const anchor = document.createElement("a");
        anchor.style.display = "none";
        anchor.download = "attack_navigator_layer.json";
        anchor.href = url;
        anchor.click();
        URL.revokeObjectURL(url);
    }

    function accordion(section) {
        accordionSelected = accordionSelected === section ? null : section;
    }
</script>

<BackButton on:back={() => dispatch("showSearch")} />
<h2>ATT&CK Powered Suit</h2>
<h3><i class="bi bi-bookmark-fill" /> Bookmarks</h3>

<table class="table">
    <thead>
        <tr>
            <th><!--Bookmark icon column--></th>
            <th>Object ID</th>
            <th>Name</th>
            {#if colorBy == "Color"}
                <th class="colorToggle" on:click={() => (colorBy = "Score")}
                    >Color <i
                        class="bi bi-toggle-on"
                        title="Switch to Color"
                    /></th
                >
            {:else if colorBy == "Score"}
                <th class="colorToggle" on:click={() => (colorBy = "Color")}
                    >Score <i
                        class="bi bi-toggle-off"
                        title="Switch to Score"
                    /></th
                >
            {/if}
            <th>Notes</th>
        </tr>
    </thead>
    <tbody>
        {#if $bookmarksStore.length == 0}
            <tr>
                <td class="nothing-found" colspan="999"
                    >Create a bookmark by clicking the <i
                        class="bi bi-bookmark-plus-fill"
                    /> next to any search result.</td
                >
            </tr>
        {/if}
        {#each $bookmarksStore as bookmark, bookmarkIdx (bookmark.id)}
            <tr out:fade>
                <td
                    ><i
                        on:click={() => removeBookmark(bookmark.id)}
                        title="Remove this bookmark"
                        class="bookmark-icon bi bi-bookmark-check-fill"
                    /></td
                >
                <td>{bookmark.id}</td>
                <td>{bookmark.name}</td>
                {#if colorBy == "Color"}
                    <td
                        ><input
                            type="color"
                            class="form-control color-picker"
                            bind:value={bookmark.color}
                            on:input={saveBookmarks}
                        /></td
                    >
                {/if}
                {#if colorBy == "Score"}
                    <td>
                        <input
                            type="number"
                            class="form-control score-input"
                            bind:value={bookmark.score}
                            on:input={saveBookmarks}
                        />
                    </td>
                {/if}
                <td
                    ><input
                        type="text"
                        class="form-control"
                        bind:value={bookmark.notes}
                        on:input={saveBookmarks}
                    /></td
                >
            </tr>
        {/each}
    </tbody>
</table>

<div class="accordion">
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button
                class="accordion-button"
                class:collapsed={accordionSelected !== "bookmarks"}
                type="button"
                on:click={() => accordion("bookmarks")}
            >
                Export Bookmarks
            </button>
        </h2>
        <div
            class="accordion-collapse collapse"
            class:show={accordionSelected === "bookmarks"}
        >
            <div class="accordion-body">
                <form on:submit={(e) => e.preventDefault()}>
                    <div class="row">
                        <div class="col">
                            <button
                                class="btn btn-primary"
                                on:click={() => exportCsv()}
                            >
                                <i class="bi bi-download" /> Export CSV
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button
                class="accordion-button"
                class:collapsed={accordionSelected !== "navigator"}
                type="button"
                on:click={() => accordion("navigator")}
            >
                Export ATT&CK Navigator Layer
            </button>
        </h2>
        <div
            class="accordion-collapse collapse"
            class:show={accordionSelected === "navigator"}
        >
            <div class="accordion-body">
                <p class="exportText">
                    Export bookmarked techniques to an ATT&CK Navigator layer.
                    Other bookmarks (e.g. software, group) are mapped to their
                    related techniques.
                </p>
                <form on:submit={(e) => e.preventDefault()}>
                    <div class="row">
                        <div class="col">
                            <div class="form-floating">
                                <select
                                    class="form-select"
                                    id="attackDomain"
                                    aria-label="Select ATT&CK domain"
                                >
                                    <option value="enterprise-attack" selected
                                        >enterprise-attack</option
                                    >
                                    <option value="mobile-attack"
                                        >mobile-attack</option
                                    >
                                    <option value="ics-attack"
                                        >ics-attack</option
                                    >
                                </select>
                                <label for="attackDomain"
                                    >ATT&amp;CK Domain</label
                                >
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-floating">
                                <input
                                    id="layerTitle"
                                    type="text"
                                    class="form-control"
                                    placeholder="Layer Title"
                                    value="Generated by ATT&CK Powered Suit"
                                    required
                                />
                                <label for="layerTitle">Layer Title</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <button
                                class="btn btn-primary"
                                on:click={() => exportAttackLayer()}
                            >
                                <i class="bi bi-download" /> Export Navigator Layer
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<style>
    .colorToggle {
        color: var(--me-ext-orange-dark);
    }

    .accordion-button {
        background-color: var(--me-core-gray-light);
    }

    .accordion-button:not(.collapsed) {
        color: var(--me-core-purple);
    }

    .accordion-button:not(.collapsed)::after {
        background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%236241c5'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z'/%3e%3c/svg%3e");
    }

    .accordion-collapse {
        padding: 1rem;
    }

    p.exportText {
        color: var(--me-core-gray);
        margin-bottom: 0.5rem;
        font-size: 10pt;
    }

    form .row {
        margin-bottom: 0.5rem;
    }

    form .row:last-child {
        margin-bottom: 0;
    }

    .bookmark-icon {
        cursor: pointer;
        color: var(--me-ext-green-dark);
        font-size: 1.4em;
    }

    .bookmark-icon:hover {
        color: var(--me-ext-green-highlighter);
    }

    .color-picker {
        display: inline-block;
        height: 2em;
        width: 2em;
        padding: 3px;
        margin: 0;
    }

    .color-picker:disabled {
        opacity: 0.25;
    }

    .score-input {
        width: 3.5em;
    }
</style>
