name: Build Extensions

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '17'
    - name: Install Build Dependencies
      run: npm ci
    - name: Run Unit Tests
      run: npm run test
    - name: Upload Coverage to CodeCov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_SECRET }}
        files: coverage/coverage-final.json
        verbose: true
    - name: Fetch ATT&CK STIX Data
      run: npm run fetch-attack
    - name: Build Search Index
      run: npm run build-index
    - name: Build Svelte Application
      run: npm run build
    - name: Build Chrome extension
      run: make chrome-ext
    - name: Package Chrome Extension
      uses: actions/upload-artifact@v4
      with:
        name: attack-powered-suit-chrome
        path: browsers/chrome/
    - name: Build Firefox extension
      run: make firefox-ext
    - name: Package Chrome Extension
      uses: actions/upload-artifact@v4
      with:
        name: attack-powered-suit-firefox
        path: browsers/firefox/
